import assert from 'node:assert/strict';
import {IntegrationStateAdapter,ACTION_CERTAINTY} from '../integration/integration-state-adapter.js';
import {PAUSE_REASON,mapSubsystemReason} from '../integration/pause-reasons.js';
import {applyStructuredPause,sanitizePause} from '../integration/pause-state-schema.js';
const a=new IntegrationStateAdapter();
assert.equal(mapSubsystemReason('MUTATION_PERSIST_FAILED'),PAUSE_REASON.RUNTIME_MUTATION_PERSIST_FAILED);
const mutation=a.pauseFromSubsystem({reason:'MUTATION_PERSIST_FAILED',side:'B',provider:'ChatGPT'});
assert.equal(mutation.pause.code,PAUSE_REASON.RUNTIME_MUTATION_PERSIST_FAILED);
assert.equal(mutation.pause.certainty,ACTION_CERTAINTY.UNKNOWN);
assert.doesNotMatch(mutation.pause.message,/No message was sent/i);
const unknown=a.pauseFromSubsystem({reason:'FUTURE_REASON',side:'C',provider:'Grok'});
assert.equal(unknown.pause.code,PAUSE_REASON.RUNTIME_UNMAPPED_SAFETY_STATE);
assert.equal(unknown.pause.certainty,ACTION_CERTAINTY.UNKNOWN);
assert.equal(unknown.pause.sourceCode,'FUTURE_REASON');
const state=applyStructuredPause({running:true,paused:false,pause:null,pauseReason:''},unknown.pause);
assert.equal(state.pause.sourceCode,'FUTURE_REASON');
const reloaded=sanitizePause(JSON.parse(JSON.stringify(state.pause)));
assert.equal(reloaded.sourceCode,'FUTURE_REASON');
const dom=a.pauseFromDomCapability({capability:'send',authorityReason:'NO_TRUSTED_AUTHORITY',side:'A',provider:'ChatGPT'});
assert.equal(dom.pause.certainty,ACTION_CERTAINTY.NO_ACTION_TAKEN);
console.log('round14-adapter: PASS');
