import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {classifyThreadLimit}=require('../thread_rollover/provider-limit-signatures.js');
const {ThreadRolloverOrchestrator}=require('../thread_rollover/thread-rollover-orchestrator.js');
const generic=classifyThreadLimit({provider:'chatgpt',regions:[{kind:'provider-notice',visible:true,text:'Start a new chat to continue'}]});
assert.equal(generic.automaticRollover,false);assert.equal(generic.state,'CORROBORATION_ONLY');
const poisoned=classifyThreadLimit({provider:'chatgpt',regions:[{kind:'assistant-response',visible:true,text:"You've reached the maximum length for this conversation"}]});
assert.equal(poisoned.state,'UNTRUSTED_TEXT_ONLY');assert.equal(poisoned.automaticRollover,false);
const hard=classifyThreadLimit({provider:'chatgpt',regions:[{kind:'system-banner',visible:true,text:"You've reached the maximum length for this conversation. Start a new chat to continue."}],composer:{present:true,disabled:true}});
assert.equal(hard.state,'HARD_THREAD_LIMIT');assert.equal(hard.automaticRollover,true);assert.equal(hard.confidence,'HIGH');
for(const provider of ['grok','claude','gemini','copilot'])assert.equal(classifyThreadLimit({provider,regions:[{kind:'provider-notice',visible:true,text:'Maximum length for this conversation. Start a new chat.'}]}).automaticRollover,false);
const calls=[];const coordinator={begin(input){calls.push(['begin',input]);return input;},transition(side,phase,patch,now){calls.push(['transition',{side,phase,patch,now}]);return {side,phase,...patch};}};
const orchestrator=new ThreadRolloverOrchestrator({coordinator,classifyLimit:classifyThreadLimit,classifyIdentityTransition:(a,b)=>a.threadKey===b.threadKey?'IDENTITY_UNCHANGED':b.kind==='surface'?'NEW_CHAT_SURFACE':'NEW_CONVERSATION_CONFIRMED'});
assert.throws(()=>orchestrator.beginAuto({rolloverId:'r1',side:'A',provider:'chatgpt',triggeringDispatchId:'d1',oldAuthority:{},limitObservation:{provider:'chatgpt',regions:[{kind:'provider-notice',visible:true,text:'Start a new chat'}]}}),/HARD_THREAD_LIMIT/);
orchestrator.beginAuto({rolloverId:'r2',side:'A',provider:'chatgpt',triggeringDispatchId:'d2',oldAuthority:{},limitObservation:{provider:'chatgpt',regions:[{kind:'system-banner',visible:true,text:'Maximum length for this conversation'}]}});
assert.equal(calls.at(-1)[1].triggerMode,'AUTO');
orchestrator.beginManual({rolloverId:'r3',side:'A',provider:'chatgpt',triggeringDispatchId:'d3',oldAuthority:{}});assert.equal(calls.at(-1)[1].triggerMode,'MANUAL');
assert.equal(orchestrator.classifyIdentityObservation({threadKey:'old'},{threadKey:'old',kind:'conversation'}).accepted,false);
assert.equal(orchestrator.classifyIdentityObservation({threadKey:'old'},{threadKey:null,kind:'surface'}).accepted,true);
console.log('round4-a: PASS');
