import assert from "node:assert/strict";
import authorityModule from "../thread_rollover/conversation-authority.js";
import ledgerModule from "../thread_rollover/dispatch-ledger.js";
import coordinatorModule from "../thread_rollover/rollover-coordinator.js";
import gateModule from "../thread_rollover/incoming-response-gate.js";
const{AUTHORITY_STATES,createConversationAuthority,revokeAuthority,nextGeneration}=authorityModule;
const{DISPATCH_STATUS,DispatchLedger}=ledgerModule;
const{PHASE,TRIGGER_MODE,RolloverCoordinator}=coordinatorModule;
const{DISPOSITION,validateIncomingResponse}=gateModule;
const oldIdentity={provider:"chatgpt",kind:"conversation",routeClass:"conversation",threadKey:"old",writable:true,provisional:false};
const newIdentity={...oldIdentity,threadKey:"new"};
const surface={provider:"chatgpt",kind:"surface",routeClass:"home",threadKey:null,writable:true,provisional:true};
assert.throws(()=>createConversationAuthority({side:"B",tabId:1,generationEpoch:1,identity:{...oldIdentity,threadKey:null},state:AUTHORITY_STATES.CONFIRMED}));
assert.throws(()=>createConversationAuthority({side:"B",tabId:1,generationEpoch:1,identity:{provider:"chatgpt",kind:"share",routeClass:"share",threadKey:"x",writable:true,provisional:false},state:AUTHORITY_STATES.CONFIRMED}));
const oldAuthority=createConversationAuthority({side:"B",tabId:10,generationEpoch:5,identity:oldIdentity,state:AUTHORITY_STATES.CONFIRMED});
const ledger=new DispatchLedger();
ledger.create({dispatchId:"normal",side:"B",tabId:10,generationEpoch:5,conversationIdentity:oldIdentity,purpose:"RELAY",payloadHash:"h",createdAt:1});
ledger.transition("normal",DISPATCH_STATUS.DISPATCHING);ledger.transition("normal",DISPATCH_STATUS.ACCEPTED,{acceptedAt:2});ledger.transition("normal",DISPATCH_STATUS.AWAITING_RESPONSE);
assert.equal(validateIncomingResponse({ledger,authority:oldAuthority,senderTabId:10,side:"B",dispatchId:"normal",generationEpoch:5,conversationIdentity:oldIdentity}).disposition,DISPOSITION.COMMIT);
assert.equal(validateIncomingResponse({ledger,authority:oldAuthority,senderTabId:10,side:"B",dispatchId:"normal",generationEpoch:4,conversationIdentity:oldIdentity}).disposition,DISPOSITION.DROP);
assert.throws(()=>new RolloverCoordinator().begin({rolloverId:"bad",side:"B",provider:"chatgpt",triggeringDispatchId:"normal",oldAuthority,triggerMode:TRIGGER_MODE.AUTO,hardLimitEvidence:{}}));
const coord=new RolloverCoordinator();
coord.begin({rolloverId:"r1",side:"B",provider:"chatgpt",triggeringDispatchId:"normal",oldAuthority,triggerMode:TRIGGER_MODE.AUTO,hardLimitEvidence:{state:"HARD_THREAD_LIMIT",automaticRollover:true},startedAt:10});
coord.transition("B",PHASE.OLD_AUTHORITY_REVOKED,{oldAuthority:revokeAuthority(oldAuthority)},11);coord.transition("B",PHASE.OPENING_NEW_CHAT,{},12);coord.transition("B",PHASE.AWAITING_NEW_IDENTITY,{},13);
const provisional=nextGeneration(oldAuthority,surface,AUTHORITY_STATES.PROVISIONAL);
coord.transition("B",PHASE.NEW_IDENTITY_VERIFIED,{candidateAuthority:provisional},14);coord.transition("B",PHASE.CONTINUITY_PENDING,{continuityDispatchId:"cont"},15);
ledger.create({dispatchId:"cont",side:"B",tabId:10,generationEpoch:6,conversationIdentity:surface,purpose:"CONTINUITY",payloadHash:"c",createdAt:15});ledger.transition("cont",DISPATCH_STATUS.DISPATCHING);ledger.transition("cont",DISPATCH_STATUS.ACCEPTED,{acceptedAt:16});ledger.transition("cont",DISPATCH_STATUS.AWAITING_RESPONSE);
assert.equal(validateIncomingResponse({ledger,coordinator:coord,senderTabId:10,side:"B",dispatchId:"cont",generationEpoch:6,conversationIdentity:newIdentity,rolloverId:"r1"}).disposition,DISPOSITION.PARK);
coord.transition("B",PHASE.CONTINUITY_SENT,{},17);coord.transition("B",PHASE.AWAITING_CONTINUITY_RESPONSE,{},18);
assert.equal(validateIncomingResponse({ledger,coordinator:coord,senderTabId:10,side:"B",dispatchId:"cont",generationEpoch:6,conversationIdentity:oldIdentity,rolloverId:"r1"}).disposition,DISPOSITION.DROP);
const confirmed=createConversationAuthority({side:"B",tabId:10,generationEpoch:6,identity:newIdentity,state:AUTHORITY_STATES.CONFIRMED});
const tx=coord.get("B");coord._bySide.set("B",Object.freeze({...tx,candidateAuthority:confirmed}));
assert.equal(validateIncomingResponse({ledger,coordinator:coord,senderTabId:10,side:"B",dispatchId:"cont",generationEpoch:6,conversationIdentity:newIdentity,rolloverId:"r1"}).disposition,DISPOSITION.COMMIT);
const bad=coord.snapshot()[0];
assert.throws(()=>new RolloverCoordinator([{...bad,phase:PHASE.COMPLETE,continuityStatus:"ACCEPTED"}]));
const manual=new RolloverCoordinator();manual.begin({rolloverId:"m1",side:"C",provider:"chatgpt",triggeringDispatchId:"normal",oldAuthority:{...oldAuthority,side:"C"},triggerMode:TRIGGER_MODE.MANUAL,startedAt:1});assert.equal(manual.get("C").triggerMode,TRIGGER_MODE.MANUAL);
console.log("round4-backend: PASS");
