import assert from "node:assert/strict";
import authorityModule from "../thread_rollover/conversation-authority.js";
import ledgerModule from "../thread_rollover/dispatch-ledger.js";
import coordinatorModule from "../thread_rollover/rollover-coordinator.js";
import gateModule from "../thread_rollover/incoming-response-gate.js";
import parkedModule from "../thread_rollover/parked-response-store.js";
const{AUTHORITY_STATES,createConversationAuthority,revokeAuthority,nextGeneration}=authorityModule;
const{DISPATCH_STATUS,DispatchLedger}=ledgerModule;
const{PHASE,TRIGGER_MODE,RolloverCoordinator}=coordinatorModule;
const{DISPOSITION,validateIncomingResponse}=gateModule;
const{ParkedResponseStore}=parkedModule;
const oldIdentity={provider:"chatgpt",kind:"conversation",routeClass:"conversation",threadKey:"old",writable:true,provisional:false};
const newIdentity={...oldIdentity,threadKey:"new"};
const otherIdentity={...oldIdentity,threadKey:"other"};
const surface={provider:"chatgpt",kind:"surface",routeClass:"home",threadKey:null,writable:true,provisional:true};
const oldAuthority=createConversationAuthority({side:"B",tabId:10,generationEpoch:5,identity:oldIdentity,state:AUTHORITY_STATES.CONFIRMED});
const ledger=new DispatchLedger();
ledger.create({dispatchId:"normal",side:"B",tabId:10,generationEpoch:5,conversationIdentity:oldIdentity,purpose:"RELAY",payloadHash:"n",createdAt:1});
ledger.transition("normal",DISPATCH_STATUS.DISPATCHING);ledger.transition("normal",DISPATCH_STATUS.ACCEPTED,{acceptedAt:2});ledger.transition("normal",DISPATCH_STATUS.AWAITING_RESPONSE);
const wrongAuthority=createConversationAuthority({side:"B",tabId:10,generationEpoch:5,identity:otherIdentity,state:AUTHORITY_STATES.CONFIRMED});
assert.equal(validateIncomingResponse({ledger,authority:wrongAuthority,senderTabId:10,side:"B",dispatchId:"normal",generationEpoch:5,conversationIdentity:otherIdentity}).disposition,DISPOSITION.DROP);
assert.throws(()=>new DispatchLedger([{...ledger.snapshot()[0],acceptedAt:null}]));
const coord=new RolloverCoordinator();
coord.begin({rolloverId:"r1",side:"B",provider:"chatgpt",triggeringDispatchId:"normal",oldAuthority,triggerMode:TRIGGER_MODE.AUTO,hardLimitEvidence:{state:"HARD_THREAD_LIMIT",automaticRollover:true},startedAt:10});
coord.transition("B",PHASE.OLD_AUTHORITY_REVOKED,{oldAuthority:revokeAuthority(oldAuthority)},11);coord.transition("B",PHASE.OPENING_NEW_CHAT,{},12);coord.transition("B",PHASE.AWAITING_NEW_IDENTITY,{},13);
const provisional=nextGeneration(oldAuthority,surface,AUTHORITY_STATES.PROVISIONAL);
coord.transition("B",PHASE.NEW_IDENTITY_VERIFIED,{candidateAuthority:provisional},14);coord.transition("B",PHASE.CONTINUITY_PENDING,{continuityDispatchId:"cont"},15);coord.transition("B",PHASE.CONTINUITY_SENT,{},16);coord.transition("B",PHASE.AWAITING_CONTINUITY_RESPONSE,{},17);
ledger.create({dispatchId:"cont",side:"B",tabId:10,generationEpoch:6,conversationIdentity:surface,purpose:"CONTINUITY",payloadHash:"c",createdAt:15});ledger.transition("cont",DISPATCH_STATUS.DISPATCHING);ledger.transition("cont",DISPATCH_STATUS.ACCEPTED,{acceptedAt:16});ledger.transition("cont",DISPATCH_STATUS.AWAITING_RESPONSE);
const envelope={senderTabId:10,side:"B",dispatchId:"cont",generationEpoch:6,conversationIdentity:newIdentity,rolloverId:"r1",text:"continuity reply"};
const first=validateIncomingResponse({ledger,coordinator:coord,...envelope});
assert.equal(first.disposition,DISPOSITION.PARK);
const parked=new ParkedResponseStore({now:()=>1000});
assert.equal(parked.park("cont",envelope).stored,true);
const confirmed=createConversationAuthority({side:"B",tabId:10,generationEpoch:6,identity:newIdentity,state:AUTHORITY_STATES.CONFIRMED});
coord.promoteCandidateAuthority("B",confirmed,18);
const saved=parked.take("cont");
assert.ok(saved);
const second=validateIncomingResponse({ledger,coordinator:coord,...saved.envelope});
assert.equal(second.disposition,DISPOSITION.COMMIT);
assert.equal(parked.size(),0);
assert.equal(validateIncomingResponse({ledger,coordinator:coord,...{...envelope,conversationIdentity:oldIdentity}}).disposition,DISPOSITION.DROP);
coord.transition("B",PHASE.COMPLETE,{},19);
assert.equal(coord.get("B").candidateAuthority.state,AUTHORITY_STATES.CONFIRMED);
const failCoord=new RolloverCoordinator();
failCoord.begin({rolloverId:"f1",side:"B",provider:"chatgpt",triggeringDispatchId:"normal",oldAuthority,triggerMode:TRIGGER_MODE.MANUAL,startedAt:20});
failCoord.fail("B","cancelled",21);
assert.equal(failCoord.get("B").failureFromPhase,PHASE.LIMIT_CONFIRMED);
assert.equal(new RolloverCoordinator(failCoord.snapshot()).get("B").oldAuthority.state,AUTHORITY_STATES.CONFIRMED);
assert.throws(()=>new RolloverCoordinator([{...failCoord.snapshot()[0],oldAuthority:revokeAuthority(oldAuthority)}]));
assert.throws(()=>new RolloverCoordinator([{...coord.snapshot()[0],phase:PHASE.COMPLETE,candidateAuthority:provisional,continuityStatus:"RESPONSE_ACCEPTED"}]));
console.log("round6-backend: PASS");
