"use strict";
const{sanitizeIdentity,sameIdentity}=require("./conversation-authority.js");
const DISPATCH_STATUS=Object.freeze({CREATED:"CREATED",DISPATCHING:"DISPATCHING",ACCEPTED:"ACCEPTED",AWAITING_RESPONSE:"AWAITING_RESPONSE",RESPONSE_COMMITTED:"RESPONSE_COMMITTED",DELIVERY_AMBIGUOUS:"DELIVERY_AMBIGUOUS",FAILED:"FAILED"});
const PURPOSES=new Set(["INITIAL","RELAY","DIRECT","MANUAL","CONTINUITY","HUMAN_REPLY"]);
const TRANSITIONS=Object.freeze({CREATED:new Set(["DISPATCHING","FAILED"]),DISPATCHING:new Set(["ACCEPTED","DELIVERY_AMBIGUOUS","FAILED"]),ACCEPTED:new Set(["AWAITING_RESPONSE","DELIVERY_AMBIGUOUS","FAILED"]),AWAITING_RESPONSE:new Set(["RESPONSE_COMMITTED","DELIVERY_AMBIGUOUS","FAILED"]),RESPONSE_COMMITTED:new Set(),DELIVERY_AMBIGUOUS:new Set(["FAILED"]),FAILED:new Set()});
function requireText(value,name){const t=String(value??"").trim();if(!t)throw new TypeError(`${name} must be a non-empty string.`);return t;}
function requireInt(value,name,min=0){const n=Number(value);if(!Number.isInteger(n)||n<min)throw new TypeError(`${name} must be an integer >= ${min}.`);return n;}
function validateLifecycle(r){
  const{status,createdAt,acceptedAt,completedAt}=r;
  if(acceptedAt!==null&&acceptedAt<createdAt)throw new Error("acceptedAt cannot precede createdAt.");
  if(completedAt!==null&&acceptedAt===null)throw new Error("completedAt requires acceptedAt.");
  if(completedAt!==null&&completedAt<acceptedAt)throw new Error("completedAt cannot precede acceptedAt.");
  if(status===DISPATCH_STATUS.CREATED&&(acceptedAt!==null||completedAt!==null))throw new Error("CREATED cannot have acceptance/completion timestamps.");
  if(status===DISPATCH_STATUS.DISPATCHING&&completedAt!==null)throw new Error("DISPATCHING cannot have completedAt.");
  if([DISPATCH_STATUS.ACCEPTED,DISPATCH_STATUS.AWAITING_RESPONSE].includes(status)&&(acceptedAt===null||completedAt!==null))throw new Error(`${status} requires acceptedAt and no completedAt.`);
  if(status===DISPATCH_STATUS.RESPONSE_COMMITTED&&(acceptedAt===null||completedAt===null))throw new Error("RESPONSE_COMMITTED requires acceptedAt and completedAt.");
  if(status===DISPATCH_STATUS.DELIVERY_AMBIGUOUS&&completedAt!==null)throw new Error("DELIVERY_AMBIGUOUS cannot have completedAt.");
  return r;
}
function freezeRecord(r){return Object.freeze({...validateLifecycle(r),conversationIdentity:r.conversationIdentity});}
class DispatchLedger{
 constructor(records=[]){this._records=new Map();for(const r of records)this.restore(r);}
 create({dispatchId,side,tabId,generationEpoch,conversationIdentity,purpose,payloadHash,createdAt=Date.now()}={}){const id=requireText(dispatchId,"dispatchId");if(this._records.has(id))throw new Error(`Dispatch ${id} already exists.`);const p=requireText(purpose,"purpose").toUpperCase();if(!PURPOSES.has(p))throw new TypeError(`Unsupported dispatch purpose: ${p}`);const r=freezeRecord({dispatchId:id,side:requireText(side,"side").toUpperCase(),tabId:requireInt(tabId,"tabId",1),generationEpoch:requireInt(generationEpoch,"generationEpoch",0),conversationIdentity:sanitizeIdentity(conversationIdentity),purpose:p,payloadHash:requireText(payloadHash,"payloadHash"),status:DISPATCH_STATUS.CREATED,createdAt:requireInt(createdAt,"createdAt",0),acceptedAt:null,completedAt:null,failureReason:""});this._records.set(id,r);return r;}
 restore(raw){if(!raw||typeof raw!=="object")throw new TypeError("dispatch record must be an object.");const id=requireText(raw.dispatchId,"dispatchId");if(this._records.has(id))throw new Error(`Duplicate persisted dispatch: ${id}`);const status=requireText(raw.status,"status");if(!Object.values(DISPATCH_STATUS).includes(status))throw new TypeError(`Unknown dispatch status: ${status}`);const p=requireText(raw.purpose,"purpose").toUpperCase();if(!PURPOSES.has(p))throw new TypeError(`Unsupported dispatch purpose: ${p}`);const r=freezeRecord({dispatchId:id,side:requireText(raw.side,"side").toUpperCase(),tabId:requireInt(raw.tabId,"tabId",1),generationEpoch:requireInt(raw.generationEpoch,"generationEpoch",0),conversationIdentity:sanitizeIdentity(raw.conversationIdentity),purpose:p,payloadHash:requireText(raw.payloadHash,"payloadHash"),status,createdAt:requireInt(raw.createdAt,"createdAt",0),acceptedAt:raw.acceptedAt==null?null:requireInt(raw.acceptedAt,"acceptedAt",0),completedAt:raw.completedAt==null?null:requireInt(raw.completedAt,"completedAt",0),failureReason:String(raw.failureReason||"")});this._records.set(id,r);return r;}
 get(id){return this._records.get(String(id||""))||null;}
 transition(dispatchId,nextStatus,patch={}){const cur=this.get(dispatchId);if(!cur)throw new Error(`Unknown dispatch: ${dispatchId}`);const next=requireText(nextStatus,"nextStatus");if(!Object.values(DISPATCH_STATUS).includes(next))throw new TypeError(`Unknown dispatch status: ${next}`);if(!TRANSITIONS[cur.status].has(next))throw new Error(`Invalid dispatch transition ${cur.status} -> ${next}.`);const u=freezeRecord({...cur,status:next,acceptedAt:patch.acceptedAt==null?cur.acceptedAt:requireInt(patch.acceptedAt,"acceptedAt",0),completedAt:patch.completedAt==null?cur.completedAt:requireInt(patch.completedAt,"completedAt",0),failureReason:patch.failureReason==null?cur.failureReason:String(patch.failureReason)});this._records.set(cur.dispatchId,u);return u;}
 validateResponse({dispatchId,side,tabId,generationEpoch,conversationIdentity}={}){const r=this.get(dispatchId);if(!r)return{ok:false,reason:"UNKNOWN_DISPATCH"};if(r.status!==DISPATCH_STATUS.AWAITING_RESPONSE)return{ok:false,reason:"DISPATCH_NOT_AWAITING_RESPONSE"};if(String(side||"").toUpperCase()!==r.side)return{ok:false,reason:"SIDE_MISMATCH"};if(Number(tabId)!==r.tabId)return{ok:false,reason:"TAB_MISMATCH"};if(Number(generationEpoch)!==r.generationEpoch)return{ok:false,reason:"GENERATION_MISMATCH"};let o;try{o=sanitizeIdentity(conversationIdentity);}catch(_){return{ok:false,reason:"MALFORMED_IDENTITY"};}const e=r.conversationIdentity;if(o.provider!==e.provider)return{ok:false,reason:"PROVIDER_MISMATCH"};if(!o.writable)return{ok:false,reason:"IDENTITY_NOT_WRITABLE"};if(e.kind==="conversation"&&!sameIdentity(o,e))return{ok:false,reason:"CONVERSATION_MISMATCH"};if(e.kind==="surface"&&o.kind!=="surface"&&o.kind!=="conversation")return{ok:false,reason:"SURFACE_TRANSITION_INVALID"};return{ok:true,reason:"AUTHORIZED"};}
 snapshot(){return[...this._records.values()].map(r=>({...r,conversationIdentity:{...r.conversationIdentity}}));}
}
module.exports={DISPATCH_STATUS,DispatchLedger};
